# Generated by Django 4.1.3 on 2022-11-22 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('breddit', '0003_alter_user_managers_alter_user_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='breddit.post'),
        ),
    ]
