# Generated by Django 4.1.3 on 2022-11-22 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breddit', '0004_alter_comment_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='votes',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='votes',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
