# Generated by Django 4.1.3 on 2022-11-23 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('breddit', '0004_upvote_remove_comment_votes_remove_post_votes_and_more'),
        ('breddit', '0005_alter_comment_votes_alter_post_votes'),
    ]

    operations = [
    ]
