# Generated by Django 4.1.3 on 2022-11-23 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breddit', '0006_merge_20221123_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='no_likes',
        ),
        migrations.AddField(
            model_name='comment',
            name='votes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
