# Generated by Django 4.1.3 on 2022-11-26 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breddit', '0007_remove_comment_no_likes_comment_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='link',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='favorites',
            field=models.ManyToManyField(blank=True, null=True, related_name='favorited_by', to='breddit.post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='no_likes',
            field=models.IntegerField(default=1),
        ),
    ]
