# Generated by Django 4.1.3 on 2022-11-26 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breddit', '0008_post_link_user_favorites_alter_post_no_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='link',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='breddit.post'),
        ),
    ]
