# Generated by Django 4.1.3 on 2022-11-26 06:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breddit', '0011_delete_upvote_post_totalvotes_alter_comment_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='totalvotes',
            field=models.ManyToManyField(blank=True, related_name='liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
