# Generated by Django 4.1.3 on 2022-11-26 06:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('breddit', '0012_alter_post_totalvotes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='no_likes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='totalvotes',
        ),
        migrations.AddField(
            model_name='post',
            name='votes',
            field=models.ManyToManyField(blank=True, related_name='liked_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='op', to='breddit.post'),
        ),
        migrations.RemoveField(
            model_name='comment',
            name='votes',
        ),
        migrations.AddField(
            model_name='comment',
            name='votes',
            field=models.ManyToManyField(blank=True, related_name='liked_comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
