# Generated by Django 4.1.3 on 2022-11-26 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breddit', '0015_remove_comment_votes_remove_post_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.CharField(max_length=512),
        ),
    ]
