# Generated by Django 4.1.3 on 2022-11-28 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breddit', '0018_comment_updated_at_user_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='random', max_length=256),
        ),
    ]
