# Generated by Django 4.1.3 on 2022-11-28 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breddit', '0021_user_banner_alter_post_category_alter_post_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(default='random', max_length=256),
        ),
    ]
