# Generated by Django 4.1.3 on 2022-11-30 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breddit', '0023_alter_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(default='oven.png', upload_to='thumbnails'),
        ),
    ]
